const translations = {
  // Header
  header: {
    home: {
      es: 'Inicio',
      en: 'Home'
    },
    createBook: {
      es: 'Crear Libro',
      en: 'Create Book'
    },
    howItWorks: {
      es: 'Cómo Funciona',
      en: 'How It Works'
    },
    createNow: {
      es: 'Crear Ahora',
      en: 'Create Now'
    }
  },

  // Footer
  footer: {
    tagline: {
      es: 'Creamos cuentos personalizados para niños con inteligencia artificial.',
      en: 'We create personalized children\'s books using artificial intelligence.'
    },
    links: {
      es: 'Enlaces',
      en: 'Links'
    },
    faq: {
      es: 'Preguntas Frecuentes',
      en: 'FAQ'
    },
    contact: {
      es: 'Contacto',
      en: 'Contact'
    },
    rights: {
      es: 'Todos los derechos reservados.',
      en: 'All rights reserved.'
    }
  },

  // Home Page
  homePage: {
    hero: {
      title: {
        es: 'Cuentos personalizados para niños',
        en: 'Personalized storybooks for children'
      },
      subtitle: {
        es: 'con inteligencia artificial',
        en: 'with artificial intelligence'
      },
      description: {
        es: 'Crea historias únicas con los nombres de tus hijos, valores personalizados y estilos de ilustración a tu gusto.',
        en: 'Create unique stories with your children\'s names, personalized values, and illustration styles of your choice.'
      },
      cta: {
        es: 'Crear Mi Libro Ahora',
        en: 'Create My Book Now'
      }
    },
    howItWorks: {
      title: {
        es: 'Cómo Funciona',
        en: 'How It Works'
      },
      step1: {
        title: {
          es: 'Personaliza tu cuento',
          en: 'Personalize your story'
        },
        description: {
          es: 'Ingresa los nombres, elige un tema y selecciona el estilo de ilustración que más te guste.',
          en: 'Enter names, choose a theme, and select the illustration style you like best.'
        }
      },
      step2: {
        title: {
          es: 'Previsualiza tu historia',
          en: 'Preview your story'
        },
        description: {
          es: 'Revisa las primeras páginas generadas por IA y confirma que es lo que buscas.',
          en: 'Review the first pages generated by AI and confirm it\'s what you want.'
        }
      },
      step3: {
        title: {
          es: 'Recibe tu libro',
          en: 'Receive your book'
        },
        description: {
          es: 'Descarga tu PDF o solicita una copia impresa que enviaremos a tu domicilio.',
          en: 'Download your PDF or request a printed copy that we\'ll ship to your address.'
        }
      }
    },
    themes: {
      title: {
        es: 'Temas Disponibles',
        en: 'Available Themes'
      },
      moral: {
        title: {
          es: 'Valores Morales',
          en: 'Moral Values'
        },
        description: {
          es: 'Historias que enseñan honestidad, amabilidad y responsabilidad.',
          en: 'Stories that teach honesty, kindness, and responsibility.'
        }
      },
      social: {
        title: {
          es: 'Educación Social',
          en: 'Social Education'
        },
        description: {
          es: 'Cuentos sobre amistad, trabajo en equipo y empatía.',
          en: 'Stories about friendship, teamwork, and empathy.'
        }
      },
      knowledge: {
        title: {
          es: 'Conocimiento',
          en: 'Knowledge'
        },
        description: {
          es: 'Aventuras educativas sobre ciencia, naturaleza y espacio.',
          en: 'Educational adventures about science, nature, and space.'
        }
      },
      fantasy: {
        title: {
          es: 'Fantasía',
          en: 'Fantasy'
        },
        description: {
          es: 'Mundos mágicos con criaturas fantásticas y emocionantes misiones.',
          en: 'Magical worlds with fantastic creatures and exciting quests.'
        }
      }
    },
    cta: {
      title: {
        es: '¿Listo para crear una historia inolvidable?',
        en: 'Ready to create an unforgettable story?'
      },
      description: {
        es: 'Dale a tus hijos el regalo de una historia donde ellos son los protagonistas.',
        en: 'Give your children the gift of a story where they are the main characters.'
      },
      button: {
        es: 'Empezar Ahora',
        en: 'Start Now'
      }
    }
  },

  // Book Creator
  bookCreator: {
    title: {
      es: 'Crea tu cuento personalizado',
      en: 'Create your personalized story'
    },
    protagonist: {
      title: {
        es: 'Información del protagonista',
        en: 'Protagonist Information'
      },
      name: {
        label: {
          es: 'Nombre del protagonista *',
          en: 'Protagonist\'s Name *'
        },
        placeholder: {
          es: 'Nombre de tu hijo/a',
          en: 'Your child\'s name'
        }
      },
      age: {
        label: {
          es: 'Edad (opcional)',
          en: 'Age (optional)'
        },
        select: {
          es: 'Selecciona la edad',
          en: 'Select age'
        },
        years: {
          es: 'años',
          en: 'years'
        }
      },
      additionalNames: {
        label: {
          es: 'Nombres adicionales (opcional)',
          en: 'Additional Names (optional)'
        },
        placeholder: {
          es: 'Nombres de hermanos, amigos o mascotas',
          en: 'Names of siblings, friends or pets'
        },
        help: {
          es: 'Separa los nombres con comas',
          en: 'Separate names with commas'
        }
      }
    },
    storyTheme: {
      title: {
        es: 'Tema de la historia',
        en: 'Story Theme'
      },
      values: {
        label: {
          es: 'Valores Morales',
          en: 'Moral Values'
        },
        description: {
          es: 'Honestidad, amabilidad, responsabilidad',
          en: 'Honesty, kindness, responsibility'
        }
      },
      social: {
        label: {
          es: 'Educación Social',
          en: 'Social Education'
        },
        description: {
          es: 'Amistad, trabajo en equipo, empatía',
          en: 'Friendship, teamwork, empathy'
        }
      },
      knowledge: {
        label: {
          es: 'Conocimiento',
          en: 'Knowledge'
        },
        description: {
          es: 'Ciencia, naturaleza, espacio',
          en: 'Science, nature, space'
        }
      },
      fantasy: {
        label: {
          es: 'Fantasía',
          en: 'Fantasy'
        },
        description: {
          es: 'Mundos mágicos y aventuras',
          en: 'Magical worlds and adventures'
        }
      },
      customization: {
        label: {
          es: 'Personalización adicional (opcional)',
          en: 'Additional Customization (optional)'
        },
        placeholder: {
          es: 'Describe algún detalle específico que te gustaría incluir en la historia',
          en: 'Describe any specific details you would like to include in the story'
        }
      }
    },
    illustrationStyle: {
      title: {
        es: 'Estilo de ilustración',
        en: 'Illustration Style'
      },
      pixar: {
        es: 'Estilo Pixar',
        en: 'Pixar Style'
      },
      disney: {
        es: 'Disney Clásico',
        en: 'Classic Disney'
      },
      watercolor: {
        es: 'Acuarela',
        en: 'Watercolor'
      },
      cartoon: {
        es: 'Caricatura',
        en: 'Cartoon'
      },
      minimalist: {
        es: 'Minimalista Moderno',
        en: 'Modern Minimalist'
      },
      preview: {
        es: 'Vista previa',
        en: 'Preview'
      }
    },
    submit: {
      button: {
        es: 'Crear Mi Cuento',
        en: 'Create My Story'
      },
      generating: {
        es: 'Generando tu cuento...',
        en: 'Generating your story...'
      }
    }
  },

  // Book Preview
  bookPreview: {
    cover: {
      es: 'Portada de',
      en: 'Cover of'
    },
    illustration: {
      es: 'Ilustración',
      en: 'Illustration'
    },
    blockedContent: {
      es: 'Contenido bloqueado',
      en: 'Content locked'
    },
    paymentPrompt: {
      title: {
        es: '¡Tu cuento está casi listo!',
        en: 'Your story is almost ready!'
      },
      description: {
        es: 'Hemos creado una historia personalizada especialmente para',
        en: 'We\'ve created a personalized story especially for'
      },
      unlock: {
        es: 'Para desbloquear el cuento completo, elige una de las siguientes opciones:',
        en: 'To unlock the full story, choose one of the following options:'
      }
    },
    digitalVersion: {
      title: {
        es: 'Versión Digital',
        en: 'Digital Version'
      },
      description: {
        es: 'Descarga inmediata en formato PDF de alta calidad',
        en: 'Immediate download in high-quality PDF format'
      },
      button: {
        es: 'Comprar Digital',
        en: 'Buy Digital'
      }
    },
    printedVersion: {
      title: {
        es: 'Versión Impresa',
        en: 'Printed Version'
      },
      description: {
        es: 'Libro físico de tapa dura enviado a tu domicilio',
        en: 'Hardcover physical book shipped to your address'
      },
      button: {
        es: 'Comprar Impreso',
        en: 'Buy Printed'
      },
      note: {
        es: '*Incluye versión digital gratis',
        en: '*Includes free digital version'
      },
      popular: {
        es: 'Más Popular',
        en: 'Most Popular'
      }
    },
    back: {
      es: 'Volver a crear otro cuento',
      en: 'Create another story'
    }
  },

  // Checkout
  checkout: {
    title: {
      es: 'Finalizar Compra',
      en: 'Complete Purchase'
    },
    summary: {
      title: {
        es: 'Resumen del Pedido',
        en: 'Order Summary'
      },
      theme: {
        es: 'Tema:',
        en: 'Theme:'
      },
      price: {
        es: 'Precio:',
        en: 'Price:'
      },
      shipping: {
        es: 'Envío:',
        en: 'Shipping:'
      },
      free: {
        es: 'Gratis',
        en: 'Free'
      },
      total: {
        es: 'Total:',
        en: 'Total:'
      },
      digitalNote: {
        es: 'Recibirás acceso inmediato a tu libro digital después del pago.',
        en: 'You will receive immediate access to your digital book after payment.'
      },
      printedNote: {
        es: 'La versión impresa será enviada dentro de los próximos 3-5 días hábiles.',
        en: 'The printed version will be shipped within the next 3-5 business days.'
      }
    },
    productType: {
      title: {
        es: 'Tipo de Producto',
        en: 'Product Type'
      },
      digital: {
        title: {
          es: 'Versión Digital',
          en: 'Digital Version'
        }
      },
      printed: {
        title: {
          es: 'Versión Impresa',
          en: 'Printed Version'
        },
        shipping: {
          es: '+ envío',
          en: '+ shipping'
        }
      }
    },
    contactInfo: {
      title: {
        es: 'Información de Contacto',
        en: 'Contact Information'
      },
      fullName: {
        es: 'Nombre completo *',
        en: 'Full name *'
      },
      email: {
        es: 'Correo electrónico *',
        en: 'Email *'
      },
      phone: {
        es: 'Teléfono *',
        en: 'Phone *'
      }
    },
    shippingAddress: {
      title: {
        es: 'Dirección de Envío',
        en: 'Shipping Address'
      },
      address: {
        es: 'Dirección *',
        en: 'Address *'
      },
      city: {
        es: 'Ciudad *',
        en: 'City *'
      },
      state: {
        es: 'Departamento *',
        en: 'State/Province *'
      },
      zip: {
        es: 'Código Postal *',
        en: 'Zip/Postal Code *'
      }
    },
    paymentMethod: {
      title: {
        es: 'Método de Pago',
        en: 'Payment Method'
      },
      card: {
        es: 'Tarjeta de Crédito / Débito',
        en: 'Credit / Debit Card'
      },
      mercadopago: {
        es: 'MercadoPago',
        en: 'MercadoPago'
      },
      pse: {
        es: 'PSE - Transferencia Bancaria',
        en: 'PSE - Bank Transfer'
      },
      placeholder: {
        es: 'Formulario de pago aquí (integración con Bold.co / MercadoPago)',
        en: 'Payment form here (integration with Bold.co / MercadoPago)'
      }
    },
    submitButton: {
      pay: {
        es: 'Pagar',
        en: 'Pay'
      },
      processing: {
        es: 'Procesando pago...',
        en: 'Processing payment...'
      }
    },
    backToPreview: {
      es: 'Volver a la vista previa',
      en: 'Back to preview'
    }
  },

  // Order Confirmation
  orderConfirmation: {
    thankYou: {
      es: '¡Gracias por tu compra!',
      en: 'Thank you for your purchase!'
    },
    orderProcessed: {
      es: 'Tu pedido ha sido procesado correctamente.',
      en: 'Your order has been successfully processed.'
    },
    orderNumber: {
      es: 'Número de pedido:',
      en: 'Order number:'
    },
    nextSteps: {
      title: {
        es: 'Próximos pasos:',
        en: 'Next steps:'
      },
      emailConfirmation: {
        title: {
          es: 'Confirmación por correo electrónico',
          en: 'Email confirmation'
        },
        description: {
          es: 'Hemos enviado un correo con los detalles de tu pedido y acceso a tu cuento.',
          en: 'We\'ve sent an email with your order details and access to your story.'
        }
      },
      download: {
        title: {
          es: 'Descarga tu cuento',
          en: 'Download your story'
        },
        description: {
          es: 'Puedes descargar tu libro personalizado inmediatamente haciendo clic en el botón de abajo.',
          en: 'You can download your personalized book immediately by clicking the button below.'
        }
      },
      shipping: {
        title: {
          es: 'Seguimiento de envío (si aplica)',
          en: 'Shipping tracking (if applicable)'
        },
        description: {
          es: 'Si ordenaste una versión impresa, recibirás una notificación con el número de seguimiento cuando tu libro sea enviado.',
          en: 'If you ordered a printed version, you will receive a notification with the tracking number when your book is shipped.'
        }
      },
      downloadButton: {
        es: 'Descargar PDF',
        en: 'Download PDF'
      },
      backToHome: {
        es: 'Volver a la página principal',
        en: 'Back to home page'
      }
    }
  },

  // Admin Dashboard
  adminDashboard: {
    title: {
      es: 'Panel de Administración',
      en: 'Admin Dashboard'
    },
    export: {
      es: 'Exportar Datos',
      en: 'Export Data'
    },
    stats: {
      totalOrders: {
        es: 'Total de Pedidos',
        en: 'Total Orders'
      },
      digitalBooks: {
        es: 'Libros Digitales',
        en: 'Digital Books'
      },
      printedBooks: {
        es: 'Libros Impresos',
        en: 'Printed Books'
      },
      totalRevenue: {
        es: 'Ingresos Totales',
        en: 'Total Revenue'
      }
    },
    tabs: {
      orders: {
        es: 'Pedidos',
        en: 'Orders'
      },
      books: {
        es: 'Libros Generados',
        en: 'Generated Books'
      },
      analytics: {
        es: 'Analíticas',
        en: 'Analytics'
      }
    },
    search: {
      placeholder: {
        es: 'Buscar por cliente, ID o título...',
        en: 'Search by customer, ID or title...'
      }
    },
    ordersTable: {
      headers: {
        id: {
          es: 'ID Pedido',
          en: 'Order ID'
        },
        customer: {
          es: 'Cliente',
          en: 'Customer'
        },
        book: {
          es: 'Libro',
          en: 'Book'
        },
        type: {
          es: 'Tipo',
          en: 'Type'
        },
        status: {
          es: 'Estado',
          en: 'Status'
        },
        date: {
          es: 'Fecha',
          en: 'Date'
        },
        total: {
          es: 'Total',
          en: 'Total'
        },
        actions: {
          es: 'Acciones',
          en: 'Actions'
        }
      },
      status: {
        completed: {
          es: 'Completado',
          en: 'Completed'
        },
        processing: {
          es: 'Procesando',
          en: 'Processing'
        },
        shipped: {
          es: 'Enviado',
          en: 'Shipped'
        }
      },
      productType: {
        digital: {
          es: 'Digital',
          en: 'Digital'
        },
        printed: {
          es: 'Impreso',
          en: 'Printed'
        }
      },
      actions: {
        view: {
          es: 'Ver',
          en: 'View'
        },
        resend: {
          es: 'Reenviar',
          en: 'Resend'
        },
        track: {
          es: 'Rastrear',
          en: 'Track'
        }
      }
    },
    placeholders: {
      books: {
        es: 'Aquí se mostrarán los libros generados',
        en: 'Generated books will be displayed here'
      },
      analytics: {
        es: 'Aquí se mostrarán las estadísticas y gráficos',
        en: 'Statistics and charts will be displayed here'
      }
    }
  },

  // Language Switcher
  languageSwitcher: {
    es: 'English',
    en: 'Español'
  }
};

export default translations; 